version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

deploy:
  machine:
    enabled: true

  working_directory: ~/client

  steps:
    - add_ssh_keys:
        fingerprints:
          - "59:74:f0:ef:33:ef:e1:75:4d:9b:a4:5a:fe:2e:26:a2"
    - checkout
    - run:
        name: Push Master to circleci-project-setup
        command: |
          git push https://github.com/lighthouse-labs/scheduler.git master:circleci-project-setup

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: circleci-project-setup
      - deploy:
          filters:
            branches:
              ignore: circleci-project-setup
          requires:
            - build